# Train Test Split

In [1]:
import os
import random
import pandas as pd

RANDOM_SEED = 42

In [2]:
# load data
mp_feature_df = pd.read_csv('./Data/featured_data/mp_elements_feat.csv')
exp_feature_df = pd.read_csv('./Data/featured_data/exp_elements_feat.csv')
mp_feature_plus_df = pd.read_csv('./Data/featured_data/mp_elements_plus_feat.csv')

In [3]:
mp_feature_df.head()

,composition,band_gap,minimum Number,maximum Number,range Number,mean Number,avg_dev Number,mode Number,minimum MendeleevNumber,maximum MendeleevNumber,...,range GSmagmom,mean GSmagmom,avg_dev GSmagmom,mode GSmagmom,minimum SpaceGroupNumber,maximum SpaceGroupNumber,range SpaceGroupNumber,mean SpaceGroupNumber,avg_dev SpaceGroupNumber,mode SpaceGroupNumber
0,Ac16S24,2.2962,16.0,89.0,73.0,45.2,35.04,16.0,14.0,88.0,...,0.000000,0.000000,0.000000,0.0,70.0,225.0,155.0,132.0,74.4,70.0
1,Ac1Ag1Te2,0.0794,47.0,89.0,42.0,60.0,14.50,52.0,14.0,90.0,...,0.000000,0.000000,0.000000,0.0,152.0,225.0,73.0,188.5,36.5,152.0
2,Ac1Cr1O3,2.0031,8.0,89.0,81.0,27.4,24.64,8.0,14.0,87.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,98.0,103.2,12.0
3,Ac1Fe1O3,0.9888,8.0,89.0,81.0,27.8,24.48,8.0,14.0,87.0,...,2.110663,0.422133,0.675412,0.0,12.0,229.0,217.0,98.0,103.2,12.0
4,Ac1Ga1O3,2.8959,8.0,89.0,81.0,28.8,24.96,8.0,14.0,87.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,65.0,64.0,12.0

In [4]:
exp_feature_df.head()

,composition,band_gap,minimum Number,maximum Number,range Number,mean Number,avg_dev Number,mode Number,minimum MendeleevNumber,maximum MendeleevNumber,...,range GSmagmom,mean GSmagmom,avg_dev GSmagmom,mode GSmagmom,minimum SpaceGroupNumber,maximum SpaceGroupNumber,range SpaceGroupNumber,mean SpaceGroupNumber,avg_dev SpaceGroupNumber,mode SpaceGroupNumber
0,Hg0.7Cd0.3Te1,0.35,48.0,80.0,32.0,61.200000,13.160000,52.0,70.0,90.0,...,0.000000,0.000000,0.000000,0.0,152.0,194.0,42.0,163.200000,11.200000,152.0
1,Lu1P1,1.30,15.0,71.0,56.0,43.000000,28.000000,15.0,41.0,83.0,...,0.002247,0.001124,0.001124,0.0,2.0,194.0,192.0,98.000000,96.000000,2.0
2,Cu3Sb1Se4,0.40,29.0,51.0,22.0,34.250000,4.187500,34.0,64.0,89.0,...,0.000000,0.000000,0.000000,0.0,14.0,225.0,211.0,112.125000,98.125000,14.0
3,Pt1Sb2,0.08,51.0,78.0,27.0,60.000000,12.000000,51.0,63.0,85.0,...,0.000000,0.000000,0.000000,0.0,166.0,225.0,59.0,185.666667,26.222222,166.0
4,Zn1In2S4,2.68,16.0,49.0,33.0,27.428571,13.061224,16.0,69.0,88.0,...,0.000000,0.000000,0.000000,0.0,70.0,194.0,124.0,107.428571,42.775510,70.0

In [5]:
mp_feature_plus_df.head()

,composition,nsites,crystal_system,space_group,volume,density,density_atomic,efermi,energy_per_atom,formation_energy_per_atom,...,range GSmagmom,mean GSmagmom,avg_dev GSmagmom,mode GSmagmom,minimum SpaceGroupNumber,maximum SpaceGroupNumber,range SpaceGroupNumber,mean SpaceGroupNumber,avg_dev SpaceGroupNumber,mode SpaceGroupNumber
0,Ac16S24,40,1,122,1118.407852,6.535149,27.960196,5.791820,-34.768478,-2.492486,...,0.000000,0.000000,0.000000,0.0,70.0,225.0,155.0,132.0,74.4,70.0
1,Ac1Ag1Te2,4,0,225,122.518406,7.997421,30.629602,6.031096,-36.203183,-0.996232,...,0.000000,0.000000,0.000000,0.0,152.0,225.0,73.0,188.5,36.5,152.0
2,Ac1Cr1O3,5,0,221,61.362845,8.848788,12.272569,6.364737,-8.862593,-3.138972,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,98.0,103.2,12.0
3,Ac1Fe1O3,5,0,221,61.797311,8.889999,12.359462,6.509045,-8.258555,-2.771539,...,2.110663,0.422133,0.675412,0.0,12.0,229.0,217.0,98.0,103.2,12.0
4,Ac1Ga1O3,5,0,221,61.455078,9.314495,12.291016,5.476935,-7.461883,-3.063253,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,65.0,64.0,12.0

In [6]:
mp_feature_df.shape, exp_feature_df.shape, mp_feature_plus_df.shape

((10342, 134), (3130, 134), (10342, 145))

<!-- ### Remove High Related Features -->

In [7]:
print(f'MP测试集大概大小：{mp_feature_df.shape[0]*0.2}')
print(f'EXP测试集大概大小：{exp_feature_df.shape[0]*0.2}')

MP测试集大概大小：2068.4
EXP测试集大概大小：626.0

In [8]:
mp_unique_comp = mp_feature_df['composition'].unique()
len(mp_unique_comp)

10305

In [9]:
# 从mp_unique_comp中随机采样组成
random.seed(RANDOM_SEED)
random_index = random.sample(range(len(mp_unique_comp)), round(len(mp_unique_comp)*0.2))
mp_test_comp = mp_unique_comp[random_index]
mp_train_set = mp_feature_df[~mp_feature_df['composition'].isin(mp_test_comp)]
mp_test_set = mp_feature_df[mp_feature_df['composition'].isin(mp_test_comp)]
print(f'MP训练集大小：{len(mp_train_set)}')
print(f'MP测试集大小：{len(mp_test_set)}')

MP训练集大小：8275
MP测试集大小：2067

In [10]:
mp_plus_train_set = mp_feature_plus_df[~mp_feature_plus_df['composition'].isin(mp_test_comp)]
mp_plus_test_set = mp_feature_plus_df[mp_feature_plus_df['composition'].isin(mp_test_comp)]
print(f'MP Plus训练集大小：{len(mp_plus_train_set)}')
print(f'MP Plus测试集大小：{len(mp_plus_test_set)}')

MP Plus训练集大小：8275
MP Plus测试集大小：2067

In [11]:
exp_unique_comp = exp_feature_df['composition'].unique()
len(exp_unique_comp)

1976

In [12]:
# 从exp_unique_comp中随机采样n种组成
random_index = random.sample(range(len(exp_unique_comp)), round(len(exp_unique_comp)*0.2))
exp_test_comp = exp_unique_comp[random_index]
exp_train_set = exp_feature_df[~exp_feature_df['composition'].isin(exp_test_comp)]
exp_test_set = exp_feature_df[exp_feature_df['composition'].isin(exp_test_comp)]
print(f'EXP训练集大小：{len(exp_train_set)}')
print(f'EXP测试集大小：{len(exp_test_set)}')

EXP训练集大小：2545
EXP测试集大小：585

In [13]:
# 混合测试集
# mp:exp = 1:1
mix_test_set = mp_test_set.sample(n=round(1*exp_test_set.shape[0])).reset_index(drop=True)

In [14]:
mix_test_set = pd.concat([mix_test_set, exp_test_set], axis=0).reset_index(drop=True)
mix_test_set = mix_test_set.sample(frac=1, random_state=RANDOM_SEED).reset_index(drop=True)
print(f'混合测试集大小：{len(mix_test_set)}')

混合测试集大小：1170

In [15]:
mix_test_set.head()

,composition,band_gap,minimum Number,maximum Number,range Number,mean Number,avg_dev Number,mode Number,minimum MendeleevNumber,maximum MendeleevNumber,...,range GSmagmom,mean GSmagmom,avg_dev GSmagmom,mode GSmagmom,minimum SpaceGroupNumber,maximum SpaceGroupNumber,range SpaceGroupNumber,mean SpaceGroupNumber,avg_dev SpaceGroupNumber,mode SpaceGroupNumber
0,Ga1Sb1,0.7800,31.0,51.0,20.0,41.000000,10.000000,31.0,74.0,85.0,...,0.0,0.0,0.0,0.0,64.0,166.0,102.0,115.00,51.000000,64.0
1,Nb6I16,0.0677,41.0,53.0,12.0,49.727273,4.760331,53.0,47.0,96.0,...,0.0,0.0,0.0,0.0,64.0,229.0,165.0,109.00,65.454545,64.0
2,Pb0.85Sn0.15Te1,0.1300,50.0,82.0,32.0,64.600000,14.790000,52.0,80.0,90.0,...,0.0,0.0,0.0,0.0,141.0,225.0,84.0,182.20,36.380000,152.0
3,In2S3,2.0000,16.0,49.0,33.0,29.200000,15.840000,16.0,75.0,88.0,...,0.0,0.0,0.0,0.0,70.0,139.0,69.0,97.60,33.120000,70.0
4,Rb1Tb1S2,2.3079,16.0,65.0,49.0,33.500000,17.500000,16.0,4.0,88.0,...,0.0,0.0,0.0,0.0,70.0,229.0,159.0,140.75,70.750000,70.0

In [16]:
# 保存
os.makedirs('./Data/train_data', exist_ok=True)
os.makedirs('./Data/test_data', exist_ok=True)
mp_train_set.to_csv('./Data/train_data/mp_train_set.csv', index=False)
mp_test_set.to_csv('./Data/test_data/mp_test_set.csv', index=False)
mp_plus_train_set.to_csv('./Data/train_data/mp_plus_train_set.csv', index=False)
mp_plus_test_set.to_csv('./Data/test_data/mp_plus_test_set.csv', index=False)
exp_train_set.to_csv('./Data/train_data/exp_train_set.csv', index=False)
exp_test_set.to_csv('./Data/test_data/exp_test_set.csv', index=False)
mix_test_set.to_csv('./Data/test_data/mix_test_set.csv', index=False)